import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  static const _storageKey = 'app_language';

  Locale _locale = const Locale('en');
  final Map<String, String> _labels = {};
  bool _initialized = false;

  Locale get locale => _locale;
  String get currentCode => _locale.languageCode;
  Map<String, String> get labels => _labels;
  bool get isInitialized => _initialized;

  LanguageProvider() {
    _setLabels('en');
  }

  Future<void> initialize() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString(_storageKey) ?? 'en';
    _locale = Locale(code);
    _setLabels(code);
    _initialized = true;
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    _locale = Locale(code);
    _setLabels(code);
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_storageKey, code);
  }

  String tr(String key, [String? fallback]) {
    return _labels[key] ?? fallback ?? key;
  }

  String trArgs(String key, List<dynamic> args, [String? fallback]) {
    final template = _labels[key] ?? fallback ?? key;
    if (args.isEmpty) return template;
    var result = template;
    for (final arg in args) {
      result = result.replaceFirst(RegExp(r'%s'), arg.toString());
    }
    return result;
  }

  void _setLabels(String code) {
    _labels.clear();
    _labels.addAll(_allTranslations[code] ?? _allTranslations['en']!);
  }
}

const _allTranslations = <String, Map<String, String>>{
  'en': {
    'app.title': 'BloomFX',
    'nav.dashboard': 'Dashboard',
    'nav.news': 'Market News',
    'nav.finance': 'Finance',
    'nav.profile': 'Profile',
    'nav.referrals': 'Referrals',
    'nav.settings': 'Settings',
    'balances': 'Balances',
    'locked': 'Tradable',
    'withdrawable': 'Withdrawable',
    'total': 'Total',
    'daily.reward.title': 'Daily Sign-In Reward',
    'daily.reward.desc': '\$%s/day bonus, claim every 24h.',
    'daily.reward.claim': 'Claim \$%s',
    'daily.reward.claimed': 'Already claimed today',
    'daily.reward.success': 'Daily reward \$%s claimed! Added to withdrawable.',
    'daily.reward.failed': 'Claim failed',
    'pending.deposit': 'Pending Deposit',
    'rank.ladder': 'Brain Box Rank Ladder',
    'copy.trades': 'Copy Trades',
    'copy.trades.limit': '%s trade(s) per day',
    'copy.trades.placeholder': 'No copy trades yet. Place your first trade.',
    'copy.trades.place': 'Place Copy Trade',
    'copy.trades.desc': 'Trades run for ~1 min (configurable) with live price movement. Profit/loss credited on completion.',
    'search': 'Search',
    'e8.account': 'E8 Account',
    'notifications': 'Notifications',
    'mark.all.read': 'Mark all read',
    'no.notifications': 'No notifications',
    'profile.title': 'Profile',
    'profile.personal.info': 'Personal Information',
    'profile.first.name': 'First Name',
    'profile.last.name': 'Last Name',
    'profile.email': 'Email',
    'profile.save': 'Save Changes',
    'profile.promo': 'Promo Codes',
    'profile.promo.hint': 'Enter Promo Code',
    'profile.promo.redeem': 'Redeem Promo',
    'profile.account.settings': 'Account Settings',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Privacy',
    'profile.language': 'Language',
    'profile.theme': 'Theme',
    'profile.security': 'Security',
    'profile.change.password': 'Change Password',
    'profile.two.factor': 'Two-Factor Authentication',
    'profile.login.history': 'Login History',
    'profile.logout': 'Logout',
    'profile.logout.confirm': 'Are you sure you want to logout?',
    'profile.logout.title': 'Logout',
    'profile.cancel': 'Cancel',
    'profile.active': 'Active',
    'profile.uploading': 'Uploading...',
    'profile.unranked': 'Unranked',
    'profile.rank.whale': 'Rank: Whale',
    'promo.success': 'Promo code applied! Bonus added to locked balance.',
    'promo.invalid': 'Invalid or expired promo code.',
    'finance.title': 'Finance',
    'finance.overview': 'Financial Overview',
    'finance.locked.balance': 'Tradable Balance',
    'finance.total.deposits': 'Approved deposits (Σ)',
    'finance.pending.deposits': 'Pending deposit amt (Σ)',
    'finance.referral.earnings': 'Referral / earnings',
    'finance.total.balance': 'Total balance',
    'finance.deposit': 'Deposit',
    'finance.withdraw': 'Withdraw',
    'finance.history': 'Deposits & withdrawals',
    'finance.no.history': 'No deposit or withdrawal requests yet.',
    'finance.crypto': 'Crypto',
    'finance.crypto.desc': 'USDT BEP-20, ERC-20, Solana, etc. — admin approval required',
    'finance.local': 'Local (Paystack)',
    'finance.local.desc': 'Pay with card, bank transfer, USSD — auto-verified, no admin needed',
    'finance.select.deposit': 'Select deposit method',
    'finance.crypto.deposit': 'Crypto Deposit',
    'finance.min.deposit': 'Minimum \$%s. Pending admin approval required.',
    'finance.network': 'Network',
    'finance.amount': 'Amount (USDT)',
    'finance.submit.crypto': 'Submit crypto deposit',
    'finance.local.deposit': 'Local Deposit (Paystack)',
    'finance.local.desc2': 'Pay with Paystack — card, bank transfer, USSD. Auto-verified, no admin needed.',
    'finance.amount.equiv': 'Amount (USDT equivalent)',
    'finance.email.receipt': 'Email (for payment receipt)',
    'finance.pay.success': 'Payment successful',
    'finance.pay.success.desc': 'Your deposit of \$%s has been confirmed and credited to your locked balance.',
    'finance.pay.failed': 'Payment failed',
    'finance.pay.processing': 'Processing...',
    'finance.pay.paystack': 'Pay with Paystack',
    'finance.secured.paystack': 'Secured by Paystack',
    'finance.select.withdraw': 'Select withdrawal method',
    'finance.available': 'Available: \$%s',
    'finance.crypto.withdraw': 'Crypto (USDT BEP-20)',
    'finance.crypto.withdraw.desc': 'Withdraw to USDT BEP-20 address — admin processes payout',
    'finance.bank': 'Bank Transfer',
    'finance.bank.desc': 'Withdraw to your local bank account',
    'finance.withdraw.crypto': 'Crypto Withdrawal',
    'finance.min.withdraw': 'Minimum withdrawal \$%s, use USDT(BEP-20) only for withdrawal. Withdrawals are processed after admin careful review.',
    'finance.withdraw.address': 'USDT (BEP-20) Address',
    'finance.withdraw.hint': '0x...',
    'finance.withdraw.submit': 'Submit withdrawal',
    'finance.pending': 'pending',
    'finance.approved': 'approved',
    'finance.rejected': 'rejected',
    'settings.title': 'Settings',
    'settings.security': 'Security Information',
    'settings.last.login.ip': 'Last Login IP',
    'settings.account.status': 'Account Status',
    'settings.banned': 'Banned',
    'settings.flagged': 'Flagged',
    'settings.support': 'Support',
    'settings.tos': 'Terms of Service',
    'settings.privacy': 'Privacy Policy',
    'settings.contact': 'Contact Support',
    'settings.theme': 'App Theme',
    'settings.theme.black': 'Black',
    'settings.theme.white': 'White',
    'settings.theme.sky': 'Sky Blue',
    'referral.title': 'Referrals',
    'referral.earn': 'Earn 8% on Every Referral Deposit',
    'referral.desc': 'When someone you refer deposits or tops up, you get 8% credited to your locked balance instantly.',
    'referral.code': 'Your Referral Code',
    'referral.my': 'My Referrals',
    'referral.total': 'Total Referrals',
    'referral.valid': 'Valid Referrals',
    'referral.earnings': 'Earnings',
    'news.title': 'Market News',
    'news.empty': 'No news yet',
    'language.title': 'Select Language',
    'language.en': 'English',
    'language.pt': 'Portuguese',
    'language.zh': 'Chinese',
    'language.ja': 'Japanese',
    'language.hi': 'Hindi',
    'ok': 'OK',
  },
  'pt': {
    'app.title': 'BloomFX',
    'nav.dashboard': 'Painel',
    'nav.news': 'Notícias',
    'nav.finance': 'Finanças',
    'nav.profile': 'Perfil',
    'nav.referrals': 'Indicações',
    'nav.settings': 'Configurações',
    'balances': 'Saldos',
    'locked': 'Negociável',
    'withdrawable': 'Sacável',
    'total': 'Total',
    'daily.reward.title': 'Recompensa Diária',
    'daily.reward.desc': 'Bônus de \$%s/dia, reivindique a cada 24h.',
    'daily.reward.claim': 'Reivindicar \$%s',
    'daily.reward.claimed': 'Já reivindicado hoje',
    'daily.reward.success': 'Recompensa diária de \$%s reivindicada!',
    'daily.reward.failed': 'Falha ao reivindicar',
    'pending.deposit': 'Depósito Pendente',
    'rank.ladder': 'Ranking Brain Box',
    'copy.trades': 'Copy Trades',
    'copy.trades.limit': '%s trade(s) por dia',
    'copy.trades.placeholder': 'Nenhum copy trade ainda.',
    'copy.trades.place': 'Fazer Copy Trade',
    'copy.trades.desc': 'Trades executam por ~1 min com movimento de preço ao vivo.',
    'search': 'Pesquisar',
    'e8.account': 'Conta E8',
    'notifications': 'Notificações',
    'mark.all.read': 'Marcar tudo lido',
    'no.notifications': 'Sem notificações',
    'profile.title': 'Perfil',
    'profile.personal.info': 'Informações Pessoais',
    'profile.first.name': 'Nome',
    'profile.last.name': 'Sobrenome',
    'profile.email': 'Email',
    'profile.save': 'Salvar',
    'profile.promo': 'Códigos Promocionais',
    'profile.promo.hint': 'Digite o código',
    'profile.promo.redeem': 'Resgatar',
    'profile.account.settings': 'Configurações da Conta',
    'profile.notifications': 'Notificações',
    'profile.privacy': 'Privacidade',
    'profile.language': 'Idioma',
    'profile.theme': 'Tema',
    'profile.security': 'Segurança',
    'profile.change.password': 'Alterar Senha',
    'profile.two.factor': 'Autenticação de Dois Fatores',
    'profile.login.history': 'Histórico de Login',
    'profile.logout': 'Sair',
    'profile.logout.confirm': 'Tem certeza que deseja sair?',
    'profile.logout.title': 'Sair',
    'profile.cancel': 'Cancelar',
    'profile.active': 'Ativo',
    'profile.uploading': 'Enviando...',
    'profile.unranked': 'Sem Rank',
    'profile.rank.whale': 'Rank: Baleia',
    'promo.success': 'Código aplicado! Bônus adicionado ao saldo negociável.',
    'promo.invalid': 'Código inválido ou expirado.',
    'finance.title': 'Finanças',
    'finance.overview': 'Visão Financeira',
    'finance.locked.balance': 'Saldo Negociável',
    'finance.total.deposits': 'Depósitos aprovados (Σ)',
    'finance.pending.deposits': 'Depósitos pendentes (Σ)',
    'finance.referral.earnings': 'Ganhos por indicação',
    'finance.total.balance': 'Saldo Total',
    'finance.deposit': 'Depositar',
    'finance.withdraw': 'Sacar',
    'finance.history': 'Depósitos e Saques',
    'finance.no.history': 'Nenhuma solicitação ainda.',
    'finance.crypto': 'Cripto',
    'finance.crypto.desc': 'USDT BEP-20, ERC-20, Solana — aprovação do admin necessária',
    'finance.local': 'Local (Paystack)',
    'finance.local.desc': 'Cartão, transferência, USSD — verificado automaticamente',
    'finance.select.deposit': 'Escolha o método',
    'finance.crypto.deposit': 'Depósito Cripto',
    'finance.min.deposit': 'Mínimo \$%s. Aprovação do admin necessária.',
    'finance.network': 'Rede',
    'finance.amount': 'Valor (USDT)',
    'finance.submit.crypto': 'Enviar depósito cripto',
    'finance.local.deposit': 'Depósito Local (Paystack)',
    'finance.local.desc2': 'Pague com Paystack — cartão, transferência, USSD.',
    'finance.amount.equiv': 'Valor (equivalente USDT)',
    'finance.email.receipt': 'Email (recibo)',
    'finance.pay.success': 'Pagamento confirmado',
    'finance.pay.success.desc': 'Seu depósito de \$%s foi creditado ao saldo negociável.',
    'finance.pay.failed': 'Pagamento falhou',
    'finance.pay.processing': 'Processando...',
    'finance.pay.paystack': 'Pagar com Paystack',
    'finance.secured.paystack': 'Protegido por Paystack',
    'finance.select.withdraw': 'Escolha o método de saque',
    'finance.available': 'Disponível: \$%s',
    'finance.crypto.withdraw': 'Cripto (USDT BEP-20)',
    'finance.crypto.withdraw.desc': 'Saque para endereço USDT BEP-20',
    'finance.bank': 'Transferência Bancária',
    'finance.bank.desc': 'Saque para sua conta bancária',
    'finance.withdraw.crypto': 'Saque Cripto',
    'finance.min.withdraw': 'Mínimo \$%s. Saldo debitado agora, admin processa.',
    'finance.withdraw.address': 'Endereço USDT (BEP-20)',
    'finance.withdraw.hint': '0x...',
    'finance.withdraw.submit': 'Solicitar saque',
    'finance.pending': 'pendente',
    'finance.approved': 'aprovado',
    'finance.rejected': 'rejeitado',
    'settings.title': 'Configurações',
    'settings.security': 'Informações de Segurança',
    'settings.last.login.ip': 'Último IP',
    'settings.account.status': 'Status da Conta',
    'settings.banned': 'Banido',
    'settings.flagged': 'Sinalizado',
    'settings.support': 'Suporte',
    'settings.tos': 'Termos de Serviço',
    'settings.privacy': 'Política de Privacidade',
    'settings.contact': 'Contatar Suporte',
    'settings.theme': 'Tema do App',
    'settings.theme.black': 'Preto',
    'settings.theme.white': 'Branco',
    'settings.theme.sky': 'Azul Celeste',
    'referral.title': 'Indicações',
    'referral.earn': 'Ganhe 8% em Cada Depósito Indicado',
    'referral.desc': 'Quando alguém que você indicou depositar, você ganha 8% creditado instantaneamente ao saldo negociável.',
    'referral.code': 'Seu Código de Indicação',
    'referral.my': 'Minhas Indicações',
    'referral.total': 'Total de Indicações',
    'referral.valid': 'Indicações Válidas',
    'referral.earnings': 'Ganhos',
    'news.title': 'Notícias do Mercado',
    'news.empty': 'Nenhuma notícia ainda',
    'language.title': 'Selecionar Idioma',
    'language.en': 'Inglês',
    'language.pt': 'Português',
    'language.zh': 'Chinês',
    'language.ja': 'Japonês',
    'language.hi': 'Hindi',
    'ok': 'OK',
  },
  'zh': {
    'app.title': 'BloomFX',
    'nav.dashboard': '仪表盘',
    'nav.news': '市场新闻',
    'nav.finance': '财务',
    'nav.profile': '个人资料',
    'nav.referrals': '推荐',
    'nav.settings': '设置',
    'balances': '余额',
    'locked': '可交易',
    'withdrawable': '可提现',
    'total': '总计',
    'daily.reward.title': '每日签到奖励',
    'daily.reward.desc': '\$%s/天奖励，每24小时领取一次。',
    'daily.reward.claim': '领取 \$%s',
    'daily.reward.claimed': '今日已领取',
    'daily.reward.success': '每日奖励 \$%s 已领取！已添加到可提现余额。',
    'daily.reward.failed': '领取失败',
    'pending.deposit': '待处理存款',
    'rank.ladder': 'Brain Box 排名阶梯',
    'copy.trades': '复制交易',
    'copy.trades.limit': '每天 %s 笔交易',
    'copy.trades.placeholder': '暂无复制交易。开始您的第一笔交易。',
    'copy.trades.place': '发起复制交易',
    'copy.trades.desc': '交易运行约1分钟，实时价格波动。完成时结算盈亏。',
    'search': '搜索',
    'e8.account': 'E8 账户',
    'notifications': '通知',
    'mark.all.read': '全部标记已读',
    'no.notifications': '暂无通知',
    'profile.title': '个人资料',
    'profile.personal.info': '个人信息',
    'profile.first.name': '名',
    'profile.last.name': '姓',
    'profile.email': '邮箱',
    'profile.save': '保存',
    'profile.promo': '优惠码',
    'profile.promo.hint': '输入优惠码',
    'profile.promo.redeem': '兑换',
    'profile.account.settings': '账户设置',
    'profile.notifications': '通知',
    'profile.privacy': '隐私',
    'profile.language': '语言',
    'profile.theme': '主题',
    'profile.security': '安全',
    'profile.change.password': '修改密码',
    'profile.two.factor': '双重认证',
    'profile.login.history': '登录历史',
    'profile.logout': '退出登录',
    'profile.logout.confirm': '确定要退出登录吗？',
    'profile.logout.title': '退出登录',
    'profile.cancel': '取消',
    'profile.active': '活跃',
    'profile.uploading': '上传中...',
    'profile.unranked': '未排名',
    'profile.rank.whale': '等级: 鲸鱼',
    'promo.success': '优惠码已应用！奖金已添加到可交易余额。',
    'promo.invalid': '优惠码无效或已过期。',
    'finance.title': '财务',
    'finance.overview': '财务概览',
    'finance.locked.balance': '可交易余额',
    'finance.total.deposits': '已批准的存款 (Σ)',
    'finance.pending.deposits': '待处理存款 (Σ)',
    'finance.referral.earnings': '推荐收入',
    'finance.total.balance': '总余额',
    'finance.deposit': '存款',
    'finance.withdraw': '提现',
    'finance.history': '存款和提现记录',
    'finance.no.history': '暂无存款或提现请求。',
    'finance.crypto': '加密货币',
    'finance.crypto.desc': 'USDT BEP-20、ERC-20、Solana等 — 需要管理员批准',
    'finance.local': '本地 (Paystack)',
    'finance.local.desc': '使用卡、银行转账、USSD支付 — 自动验证',
    'finance.select.deposit': '选择存款方式',
    'finance.crypto.deposit': '加密货币存款',
    'finance.min.deposit': '最低 \$%s。需要管理员批准。',
    'finance.network': '网络',
    'finance.amount': '金额 (USDT)',
    'finance.submit.crypto': '提交加密货币存款',
    'finance.local.deposit': '本地存款 (Paystack)',
    'finance.local.desc2': '使用Paystack支付 — 卡、银行转账、USSD。',
    'finance.amount.equiv': '金额 (USDT等值)',
    'finance.email.receipt': '邮箱 (接收收据)',
    'finance.pay.success': '支付成功',
    'finance.pay.success.desc': '您的 \$%s 存款已确认并记入可交易余额。',
    'finance.pay.failed': '支付失败',
    'finance.pay.processing': '处理中...',
    'finance.pay.paystack': '使用Paystack支付',
    'finance.secured.paystack': '由Paystack保护',
    'finance.select.withdraw': '选择提现方式',
    'finance.available': '可用: \$%s',
    'finance.crypto.withdraw': '加密货币 (USDT BEP-20)',
    'finance.crypto.withdraw.desc': '提现到USDT BEP-20地址 — 管理员处理',
    'finance.bank': '银行转账',
    'finance.bank.desc': '提现到您的本地银行账户',
    'finance.withdraw.crypto': '加密货币提现',
    'finance.min.withdraw': '最低 \$%s。立即扣除可提现余额，管理员处理。',
    'finance.withdraw.address': 'USDT (BEP-20) 地址',
    'finance.withdraw.hint': '0x...',
    'finance.withdraw.submit': '提交提现',
    'finance.pending': '待处理',
    'finance.approved': '已批准',
    'finance.rejected': '已拒绝',
    'settings.title': '设置',
    'settings.security': '安全信息',
    'settings.last.login.ip': '上次登录IP',
    'settings.account.status': '账户状态',
    'settings.banned': '已封禁',
    'settings.flagged': '已标记',
    'settings.support': '支持',
    'settings.tos': '服务条款',
    'settings.privacy': '隐私政策',
    'settings.contact': '联系支持',
    'settings.theme': '应用主题',
    'settings.theme.black': '黑色',
    'settings.theme.white': '白色',
    'settings.theme.sky': '天蓝色',
    'referral.title': '推荐',
    'referral.earn': '每次推荐存款赚取8%',
    'referral.desc': '当您推荐的人存款时，您将获得8%即时计入可交易余额。',
    'referral.code': '您的推荐码',
    'referral.my': '我的推荐',
    'referral.total': '推荐总数',
    'referral.valid': '有效推荐',
    'referral.earnings': '收入',
    'news.title': '市场新闻',
    'news.empty': '暂无新闻',
    'language.title': '选择语言',
    'language.en': '英语',
    'language.pt': '葡萄牙语',
    'language.zh': '中文',
    'language.ja': '日语',
    'language.hi': '印地语',
    'ok': '确定',
  },
  'ja': {
    'app.title': 'BloomFX',
    'nav.dashboard': 'ダッシュボード',
    'nav.news': 'マーケットニュース',
    'nav.finance': '財務',
    'nav.profile': 'プロフィール',
    'nav.referrals': '紹介',
    'nav.settings': '設定',
    'balances': '残高',
    'locked': '取引可能',
    'withdrawable': '引き出し可能',
    'total': '合計',
    'daily.reward.title': 'デイリーサインインボーナス',
    'daily.reward.desc': '\$%s/日のボーナス、24時間ごとに受け取り可能。',
    'daily.reward.claim': '\$%sを受け取る',
    'daily.reward.claimed': '本日はすでに受け取り済み',
    'daily.reward.success': 'デイリーボーナス \$%s を受け取りました！',
    'daily.reward.failed': '受け取り失敗',
    'pending.deposit': '保留中の入金',
    'rank.ladder': 'Brain Box ランクラダー',
    'copy.trades': 'コピートレード',
    'copy.trades.limit': '1日%sトレード',
    'copy.trades.placeholder': 'コピートレードはまだありません。',
    'copy.trades.place': 'コピートレードを実行',
    'copy.trades.desc': 'トレードは約1分間実行され、リアルタイムの価格変動があります。',
    'search': '検索',
    'e8.account': 'E8アカウント',
    'notifications': '通知',
    'mark.all.read': 'すべて既読にする',
    'no.notifications': '通知はありません',
    'profile.title': 'プロフィール',
    'profile.personal.info': '個人情報',
    'profile.first.name': '名',
    'profile.last.name': '姓',
    'profile.email': 'メール',
    'profile.save': '保存',
    'profile.promo': 'プロモコード',
    'profile.promo.hint': 'プロモコードを入力',
    'profile.promo.redeem': '引き換え',
    'profile.account.settings': 'アカウント設定',
    'profile.notifications': '通知',
    'profile.privacy': 'プライバシー',
    'profile.language': '言語',
    'profile.theme': 'テーマ',
    'profile.security': 'セキュリティ',
    'profile.change.password': 'パスワード変更',
    'profile.two.factor': '二段階認証',
    'profile.login.history': 'ログイン履歴',
    'profile.logout': 'ログアウト',
    'profile.logout.confirm': 'ログアウトしてもよろしいですか？',
    'profile.logout.title': 'ログアウト',
    'profile.cancel': 'キャンセル',
    'profile.active': 'アクティブ',
    'profile.uploading': 'アップロード中...',
    'profile.unranked': '未ランク',
    'profile.rank.whale': 'ランク: クジラ',
    'promo.success': 'プロモコードが適用されました！取引可能残高に追加されました。',
    'promo.invalid': '無効または期限切れのプロモコードです。',
    'finance.title': '財務',
    'finance.overview': '財務概要',
    'finance.locked.balance': '取引可能残高',
    'finance.total.deposits': '承認済み入金 (Σ)',
    'finance.pending.deposits': '保留中の入金 (Σ)',
    'finance.referral.earnings': '紹介収入',
    'finance.total.balance': '総残高',
    'finance.deposit': '入金',
    'finance.withdraw': '引き出し',
    'finance.history': '入金と引き出し',
    'finance.no.history': '入金または引き出しリクエストはまだありません。',
    'finance.crypto': '暗号通貨',
    'finance.crypto.desc': 'USDT BEP-20、ERC-20、Solanaなど — 管理者の承認が必要',
    'finance.local': 'ローカル (Paystack)',
    'finance.local.desc': 'カード、銀行振込、USSD — 自動検証',
    'finance.select.deposit': '入金方法を選択',
    'finance.crypto.deposit': '暗号通貨入金',
    'finance.min.deposit': '最低 \$%s。管理者の承認が必要です。',
    'finance.network': 'ネットワーク',
    'finance.amount': '金額 (USDT)',
    'finance.submit.crypto': '暗号通貨入金を送信',
    'finance.local.deposit': 'ローカル入金 (Paystack)',
    'finance.local.desc2': 'Paystackで支払う — カード、銀行振込、USSD。',
    'finance.amount.equiv': '金額 (USDT相当)',
    'finance.email.receipt': 'メール (領収書用)',
    'finance.pay.success': '支払い成功',
    'finance.pay.success.desc': '\$%s の入金が確認され、取引可能残高に追加されました。',
    'finance.pay.failed': '支払い失敗',
    'finance.pay.processing': '処理中...',
    'finance.pay.paystack': 'Paystackで支払う',
    'finance.secured.paystack': 'Paystackにより保護',
    'finance.select.withdraw': '引き出し方法を選択',
    'finance.available': '利用可能: \$%s',
    'finance.crypto.withdraw': '暗号通貨 (USDT BEP-20)',
    'finance.crypto.withdraw.desc': 'USDT BEP-20アドレスに引き出し',
    'finance.bank': '銀行振込',
    'finance.bank.desc': '地元の銀行口座に引き出し',
    'finance.withdraw.crypto': '暗号通貨の引き出し',
    'finance.min.withdraw': '最低 \$%s。引き出し可能残高から即時差引、管理者が処理。',
    'finance.withdraw.address': 'USDT (BEP-20) アドレス',
    'finance.withdraw.hint': '0x...',
    'finance.withdraw.submit': '引き出しを送信',
    'finance.pending': '保留中',
    'finance.approved': '承認済み',
    'finance.rejected': '拒否済み',
    'settings.title': '設定',
    'settings.security': 'セキュリティ情報',
    'settings.last.login.ip': '最終ログインIP',
    'settings.account.status': 'アカウント状態',
    'settings.banned': 'BAN済み',
    'settings.flagged': 'フラグ済み',
    'settings.support': 'サポート',
    'settings.tos': '利用規約',
    'settings.privacy': 'プライバシーポリシー',
    'settings.contact': 'サポートに連絡',
    'settings.theme': 'アプリテーマ',
    'settings.theme.black': 'ブラック',
    'settings.theme.white': 'ホワイト',
    'settings.theme.sky': 'スカイブルー',
    'referral.title': '紹介',
    'referral.earn': '紹介入金ごとに8%獲得',
    'referral.desc': '紹介した人が入金すると、8%が取引可能残高に即時加算されます。',
    'referral.code': '紹介コード',
    'referral.my': '紹介一覧',
    'referral.total': '紹介数',
    'referral.valid': '有効な紹介',
    'referral.earnings': '収入',
    'news.title': 'マーケットニュース',
    'news.empty': 'ニュースはまだありません',
    'language.title': '言語を選択',
    'language.en': '英語',
    'language.pt': 'ポルトガル語',
    'language.zh': '中国語',
    'language.ja': '日本語',
    'language.hi': 'ヒンディー語',
    'ok': 'OK',
  },
  'hi': {
    'app.title': 'BloomFX',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.news': 'बाज़ार समाचार',
    'nav.finance': 'वित्त',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.referrals': 'रेफरल',
    'nav.settings': 'सेटिंग्स',
    'balances': 'शेष राशि',
    'locked': 'व्यापार योग्य',
    'withdrawable': 'निकासी योग्य',
    'total': 'कुल',
    'daily.reward.title': 'दैनिक साइन-इन पुरस्कार',
    'daily.reward.desc': '\$%s/दिन बोनस, हर 24 घंटे में दावा करें।',
    'daily.reward.claim': '\$%s दावा करें',
    'daily.reward.claimed': 'आज पहले ही दावा किया',
    'daily.reward.success': 'दैनिक पुरस्कार \$%s दावा किया!',
    'daily.reward.failed': 'दावा विफल',
    'pending.deposit': 'लंबित जमा',
    'rank.ladder': 'Brain Box रैंक सीढ़ी',
    'copy.trades': 'कॉपी ट्रेड',
    'copy.trades.limit': 'प्रतिदिन %s ट्रेड',
    'copy.trades.placeholder': 'अभी तक कोई कॉपी ट्रेड नहीं।',
    'copy.trades.place': 'कॉपी ट्रेड करें',
    'copy.trades.desc': 'ट्रेड ~1 मिनट तक चलते हैं लाइव मूल्य आंदोलन के साथ।',
    'search': 'खोजें',
    'e8.account': 'E8 खाता',
    'notifications': 'सूचनाएं',
    'mark.all.read': 'सभी पढ़े हुए चिह्नित करें',
    'no.notifications': 'कोई सूचना नहीं',
    'profile.title': 'प्रोफ़ाइल',
    'profile.personal.info': 'व्यक्तिगत जानकारी',
    'profile.first.name': 'पहला नाम',
    'profile.last.name': 'अंतिम नाम',
    'profile.email': 'ईमेल',
    'profile.save': 'सहेजें',
    'profile.promo': 'प्रोमो कोड',
    'profile.promo.hint': 'प्रोमो कोड दर्ज करें',
    'profile.promo.redeem': 'भुनाएं',
    'profile.account.settings': 'खाता सेटिंग्स',
    'profile.notifications': 'सूचनाएं',
    'profile.privacy': 'गोपनीयता',
    'profile.language': 'भाषा',
    'profile.theme': 'थीम',
    'profile.security': 'सुरक्षा',
    'profile.change.password': 'पासवर्ड बदलें',
    'profile.two.factor': 'दो-चरणीय प्रमाणीकरण',
    'profile.login.history': 'लॉगिन इतिहास',
    'profile.logout': 'लॉग आउट',
    'profile.logout.confirm': 'क्या आप लॉग आउट करना चाहते हैं?',
    'profile.logout.title': 'लॉग आउट',
    'profile.cancel': 'रद्द करें',
    'profile.active': 'सक्रिय',
    'profile.uploading': 'अपलोड हो रहा है...',
    'profile.unranked': 'अनरैंक्ड',
    'profile.rank.whale': 'रैंक: व्हेल',
    'promo.success': 'प्रोमो कोड लागू! बोनस व्यापार योग्य शेष में जोड़ा गया।',
    'promo.invalid': 'अमान्य या समाप्त प्रोमो कोड।',
    'finance.title': 'वित्त',
    'finance.overview': 'वित्तीय अवलोकन',
    'finance.locked.balance': 'व्यापार योग्य शेष',
    'finance.total.deposits': 'स्वीकृत जमा (Σ)',
    'finance.pending.deposits': 'लंबित जमा राशि (Σ)',
    'finance.referral.earnings': 'रेफरल कमाई',
    'finance.total.balance': 'कुल शेष',
    'finance.deposit': 'जमा करें',
    'finance.withdraw': 'निकासी',
    'finance.history': 'जमा और निकासी',
    'finance.no.history': 'अभी तक कोई जमा या निकासी अनुरोध नहीं।',
    'finance.crypto': 'क्रिप्टो',
    'finance.crypto.desc': 'USDT BEP-20, ERC-20, Solana — प्रशासक अनुमोदन आवश्यक',
    'finance.local': 'स्थानीय (Paystack)',
    'finance.local.desc': 'कार्ड, बैंक ट्रांसफर, USSD — स्वचालित सत्यापन',
    'finance.select.deposit': 'जमा विधि चुनें',
    'finance.crypto.deposit': 'क्रिप्टो जमा',
    'finance.min.deposit': 'न्यूनतम \$%s। प्रशासक अनुमोदन आवश्यक।',
    'finance.network': 'नेटवर्क',
    'finance.amount': 'राशि (USDT)',
    'finance.submit.crypto': 'क्रिप्टो जमा सबमिट करें',
    'finance.local.deposit': 'स्थानीय जमा (Paystack)',
    'finance.local.desc2': 'Paystack से भुगतान करें — कार्ड, बैंक ट्रांसफर, USSD।',
    'finance.amount.equiv': 'राशि (USDT समतुल्य)',
    'finance.email.receipt': 'ईमेल (रसीद के लिए)',
    'finance.pay.success': 'भुगतान सफल',
    'finance.pay.success.desc': '\$%s की जमा की पुष्टि हो गई है और व्यापार योग्य शेष में जोड़ दी गई है।',
    'finance.pay.failed': 'भुगतान विफल',
    'finance.pay.processing': 'प्रसंस्करण...',
    'finance.pay.paystack': 'Paystack से भुगतान करें',
    'finance.secured.paystack': 'Paystack द्वारा सुरक्षित',
    'finance.select.withdraw': 'निकासी विधि चुनें',
    'finance.available': 'उपलब्ध: \$%s',
    'finance.crypto.withdraw': 'क्रिप्टो (USDT BEP-20)',
    'finance.crypto.withdraw.desc': 'USDT BEP-20 पते पर निकासी',
    'finance.bank': 'बैंक ट्रांसफर',
    'finance.bank.desc': 'अपने स्थानीय बैंक खाते में निकासी',
    'finance.withdraw.crypto': 'क्रिप्टो निकासी',
    'finance.min.withdraw': 'न्यूनतम \$%s। प्रशासक द्वारा संसाधित।',
    'finance.withdraw.address': 'USDT (BEP-20) पता',
    'finance.withdraw.hint': '0x...',
    'finance.withdraw.submit': 'निकासी सबमिट करें',
    'finance.pending': 'लंबित',
    'finance.approved': 'स्वीकृत',
    'finance.rejected': 'अस्वीकृत',
    'settings.title': 'सेटिंग्स',
    'settings.security': 'सुरक्षा जानकारी',
    'settings.last.login.ip': 'अंतिम लॉगिन IP',
    'settings.account.status': 'खाता स्थिति',
    'settings.banned': 'प्रतिबंधित',
    'settings.flagged': 'चिह्नित',
    'settings.support': 'सहायता',
    'settings.tos': 'सेवा की शर्तें',
    'settings.privacy': 'गोपनीयता नीति',
    'settings.contact': 'सहायता से संपर्क करें',
    'settings.theme': 'ऐप थीम',
    'settings.theme.black': 'काला',
    'settings.theme.white': 'सफेद',
    'settings.theme.sky': 'आसमानी नीला',
    'referral.title': 'रेफरल',
    'referral.earn': 'हर रेफरल जमा पर 8% कमाएं',
    'referral.desc': 'जब आपके द्वारा रेफर किया गया व्यक्ति जमा करता है, तो आपको 8% तुरंत व्यापार योग्य शेष में मिलता है।',
    'referral.code': 'आपका रेफरल कोड',
    'referral.my': 'मेरे रेफरल',
    'referral.total': 'कुल रेफरल',
    'referral.valid': 'मान्य रेफरल',
    'referral.earnings': 'कमाई',
    'news.title': 'बाज़ार समाचार',
    'news.empty': 'अभी तक कोई समाचार नहीं',
    'language.title': 'भाषा चुनें',
    'language.en': 'अंग्रेज़ी',
    'language.pt': 'पुर्तगाली',
    'language.zh': 'चीनी',
    'language.ja': 'जापानी',
    'language.hi': 'हिंदी',
    'ok': 'ठीक',
  },
};

extension AppTranslations on BuildContext {
  String tr(String key, [String? fallback]) {
    return Provider.of<LanguageProvider>(this, listen: false).tr(key, fallback);
  }

  String trArgs(String key, List<dynamic> args, [String? fallback]) {
    return Provider.of<LanguageProvider>(this, listen: false).trArgs(key, args, fallback);
  }
}
